name: ROASMI

channels:
  - conda-forge
  - pytorch
  - rdkit

dependencies:
  - python>=3.8
  - flask>=1.1.2
  - gunicorn>=20.0.4
  - hyperopt>=0.2.5
  - joblib>=0.17.0
  - matplotlib>=3.3.2
  - numpy>=1.19.1
  - networkx>=2.5|<3
  - pandas>=1.1.3
  - pandas-flavor>=0.2.0
  - pip>=22.1.2
  - pytorch>=1.6.0
  - rdkit>=2020.09.1
  - scikit-learn>=0.23.2|<1
  - scipy>=1.4.1
  - tensorboardX>=2.1
  - torchvision>=0.7.0
  - tqdm>=4.45.2
  - pip:
    - typed-argument-parser>=1.6.0
    - git+https://github.com/bp-kelley/descriptastorus
